# 1. The clean URL (Notice we removed the ?user=... part)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres

# 2. The Username (Your project specific user)
spring.datasource.username=postgres.yqtpvifumfmopquuzaer

# 3. The Password (Paste your actual password here)
spring.datasource.password=5v7g!%/UG8X!Bnr

# 4. The Driver and JPA settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate